// <auto-generated />
namespace wildrydes.net.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class currentstate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(currentstate));
        
        string IMigrationMetadata.Id
        {
            get { return "202508191721056_current-state"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
